
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bali_surfing_development

test:
  <<: *default
  database: bali_surfing_test

production:
  <<: *default
  host: <%= ENV['database_host'] %>
  database: <%= ENV['database_name'] %>
  username: <%= ENV['database_user'] %>
  password: <%= ENV['database_pass'] %>
