# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f96a93ef97dd04c70621489fb9d5e6d1551aac58d5994026dc9aa4b50353db44a7fb7a1c920b5c33d956e3ec76475e387c73144af0a88a417093e6c9ca4d891

test:
  secret_key_base: 5f0d37fd5f62fd6290d91699696608b109d48bd24c2076ad94db8487f2e8eb3f1e266cdd052df81ac57c871f20de59b90201455139ef4612ac978eeea4d189af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_key_base"] %>
